Example of using Scalatest to catch an exception from a future.
